config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :stores, only: [:index, :show, :new, :create] do
    resources :items, only: [:new, :create]
  end
  # Defines the root path route ("/")
  root "stores#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  has_many :store_items
  has_many :stores, through: :store_items

  validates :name, :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user

  has_many :store_items
  has_many :items, through: :store_items

  validates :name, :icon, presence: true
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
  belongs_to :store
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stores
  has_many :items

  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :email, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password)
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @store = Store.find(params[:store_id])

    if @store.user == current_user
      @item = Item.new
    else
      flash[:alert] = 'You can only create items from your stores'
      redirect_to stores_path
    end
  end

  def create
    store = Store.find_by_id(params[:store_id])
    @item = store.items.new(item_params)

    if @item.save
      join = StoreItem.create(store_id: store.id, item_id: @item.id)
      if join.nil?
        flash[:alert] = @item.errors.messages
        render :new
      else
        redirect_to store_path(store.id)
      end
    else
      flash[:alert] = @item.errors.messages
      render :new
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :amount).merge(user_id: current_user.id)
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!, except: :splash

  # GET /stores or /stores.json
  def index
    @stores = Store.where(user_id: current_user.id)
  end

  # GET /stores/1 or /stores/1.json
  def show
    @store = Store.find(params[:id])
    if @store.user != current_user
      flash[:alert] = 'You can only see what you created'
      redirect_to stores_path
    end
    @items = @store.items.order(created_at: :desc)
    @total = @items.sum(:amount)
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  def create
    store = Store.new(store_params)

    if store.save
      redirect_to stores_path
    else
      flash[:alert] = 'store not created'
      render :new
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def store_params
    params.require(:store).permit(:name, :icon).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/items/new.html.erb
<%= render 'shared/form', model: @item, path: store_items_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'K Mall', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Stores', stores_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to "Logout", destroy_user_session_path, method: 'delete', :class => 'nav-link' %>
          <% else %>
            <%= link_to "Login", new_user_session_path, :class => 'nav-link' %>
          <% end %>
        </li>
      </ul>
    </div>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        <strong><%= current_user.name %></strong>.
      <% end %>
    </p>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kmall</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    
    <div class="container mt-3">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_with model: model, url: path, class: "d-flex flex-column justify-content-between align-items-between" do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, placeholder: 'Name', required: true, autofocus: true, class: "form-control" %>
  </div>
  <% if model.is_a?(Item) %>
    <div class="mb-3">
      <%= form.label :amount, class: "form-label" %>
      <%= form.number_field :amount, placeholder: '0', required: true, class: "form-control" %>
    </div>
  <% elsif model.is_a?(Store) %>
    <div class="mb-3">
      <%= form.label :icon, class: "form-label" %>
      <%= form.text_field :icon, placeholder: 'Icon', required: true, class: "form-control" %>
    </div>
  <% end %>
  <%= form.submit 'Save', class: "btn btn-primary", data:  { turbo: false } %>
<% end %>

app/views/stores/index.html.erb
<div class="container d-flex flex-column justify-content-center">
  <% if user_signed_in? %>
    <div class="d-flex flex-column justify-content-between align-items-between" style="height: 80vh">
      <h1 class="mb-3">Stores</h1>

      <div>
        <% @stores.each do |store| %>
        <div class="card mb-1">
          <div class="card-body">
            <div class="row">
              <div class="col">
                <img src="<%=store.icon %>", alt="Icon pic", height="40px">
              </div>
              <div class="col">
                <%= link_to store.name, store_path(store) %>
              </div>
              <div class="col">
                $<%= store.items.sum(:amount) %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    </div>
    <%= link_to "Add new store", new_store_path, class: "btn btn-success mt-3" %>
  </div>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn-primary mb-2" %><br>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-info" %>
  <% end %>
</div>

app/views/stores/new.html.erb
<%= render 'shared/form', model: @store, path: stores_path %>

app/views/stores/show.html.erb
<div class="d-flex flex-column justify-content-between align-items-between" style="height: 80vh">
  <div class="row">
    <div class="col-8">
      <h2><%= @store.name %></h2>
    </div>
    <div class="col-4">
      <p>$<%= @total %></p>
    </div>
  </div>

  <div>
    <% @items.each do |item| %>
      <div class="card mb-2">
        <div class="card-body">
          <div class="row">
            <div class="col-8">
              <%= item.name %>
            </div>
            <div class="col-4">
              $<%= item.amount %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="d-flex flex-column justify-content-between align-items-between">
    <%= link_to "Add new Item", new_store_item_path(@store), class: "btn btn-success" %> <br>
    <%= link_to "Back", stores_path, class: "btn btn-secondary" %>
  </div>
</div>